version: '3.8'
services:
  nest-api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - prisma
    env_file:
      - .env.local

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env.local
    volumes:
      - mysql:/var/lib/mysql/data

  prisma:
    build: .
    command: npx prisma generate
    depends_on:
      - mysql
    env_file:
      - .env.local

volumes:
  mysql:
    name: nest-db
