version: '3.8'

services:
  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dash'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'qwe123'
    ports:
      - '3306:3306'
    volumes: 
      - prisma:/var/lib/mysql
volumes:
  prisma: