name: Merge Branch on Tag

on:
  push:
    tags:
      - 'QA-*'
      - 'PROD-*'

jobs:
  merge_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      run: |
        # Extrair o nome da branch do tag
        branch=$(echo "${GITHUB_REF#refs/tags/}" | cut -d'-' -f2-)
        
        # Verificar se é QA ou PROD
        if [[ $branch == "QA"* ]]; then
          base_branch="develop"
        elif [[ $branch == "PROD"* ]]; then
          base_branch="main"
        fi
        
        # Criar o pull request
        gh pr create --base $base_branch --head $branch --title "Merge $branch into $base_branch" --body "Automatically created pull request to merge $branch into $base_branch"
        
    - name: Merge Pull Request
      run: |
        # Extrair o nome da branch do tag
        branch=$(echo "${GITHUB_REF#refs/tags/}" | cut -d'-' -f2-)
        
        # Verificar se é QA ou PROD
        if [[ $branch == "QA"* ]]; then
          base_branch="develop"
        elif [[ $branch == "PROD"* ]]; then
          base_branch="main"
        fi
        
        # Fundir o pull request
        gh pr merge --auto --merge --squash --delete-branch
        
    - name: Restore Develop Branch on Merge Failure
      if: failure()
      run: |
        # Restaurar a branch develop sem as alterações da branch atual
        git checkout develop
        git reset --hard HEAD^

    - name: Resolve Conflicts
      if: failure()
      run: |
        # Solicitar ao desenvolvedor para resolver conflitos
        echo "Houve conflitos ao realizar o merge. Por favor, resolva os conflitos e tente novamente."
