name: Merge branches on tag

on:
  push:
    tags:
      - 'QA-*'
      - 'PROD-*'

jobs:
  merge_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/QA-.* ]]; then
            git checkout develop
            git merge --no-ff ${{ github.ref }}
          elif [[ ${{ github.ref }} =~ ^refs/tags/PROD-.* ]]; then
            git checkout main
            git merge --no-ff ${{ github.ref }}
            git branch -d $(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          fi

      - name: Push changes
        run: git push origin HEAD

  restore_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Restore develop branch on merge request rejection
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
        run: git fetch origin develop && git reset --hard origin/develop
